# Generated by Django 3.2.16 on 2022-11-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo2app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2022-11-10'),
            preserve_default=False,
        ),
    ]
